### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by h2dyn** [ZrO2Bit/Rane_RCE_Test#1]
{'errCode': 0, 'errMsg': '校验失败'}
0 /game/fbStart {'errCode': 3, 'errMsg': '时序异常'}
这个怎么解决？

**Comment by ZrO2Bit** [comment]
校验失败是正常的，因为最开始登录发的空包，不影响后续的发送，时序异常是因为在不正常登录的情况下每个ts值只能对应发送一次请求，如果多次运行软件每次需要适当增大ts值。ts值每日重置

**Comment by h2dyn** [comment]
> 校验失败是正常的，因为最开始登录发的空包，不影响后续的发送，时序异常是因为在不正常登录的情况下每个ts值只能对应发送一次请求，如果多次运行软件每次需要适当增大ts值。ts值每日重置

ok，感谢

**Comment by QAQYJY** [comment]
老哥能直接给出抢会员的链接吗 python有点看不懂。。。

**Comment by ZrO2Bit** [comment]
开源代码仅作为逆向学习的过程记录，同时为经纬科技提出技术警示，请勿干扰游戏正常进程
