### ISSUE TITLE
问题出错 有时候也提示服务器出错

### ISSUE THREAD

**Issue by Ljkkkkk** [ZrO2Bit/Rane_RCE_Test#3]
{"gfc":812,"id":106}
7372306150c5718a9a9fcaca2cfb13e2db25edcdcb817fdc1d5fc8fc311de59ad64a35b5e70cf5d57866fa13bb76578590
{'errCode': 0, 'errMsg': '校验失败'}
10000 /game/fbStart {'errCode': 3, 'errMsg': '时序异常'}
10001 /game/fbSingle {'errCode': 3, 'errMsg': '时序异常'}
999999891 /game/fbSingle {'errCode': 0, 'errMsg': '服务器出错'}

**Comment by ZrO2Bit** [comment]
有部分账号就是如此，建议自己抓login的包填进去测试一下

**Comment by adhyc520** [comment]
0 /game/exchange {'errCode': 3, 'errMsg': '时序异常'}请问登录已经返回了账号数据了，但是用单人刷分就这样，请问怎么解决

**Comment by ZrO2Bit** [comment]
增大ts的值，@adhyc520

**Comment by adhyc520** [comment]
好的，还有因为不会python 请问time.sleep(10)是需要引入import time吗，我这边总报错

**Comment by ZrO2Bit** [comment]
不会python建议放弃，本软件仅作为逆向学习过程的记录同时提出警示，禁止干扰游戏正常运营

**Comment by adhyc520** [comment]
请问ts的含义是什么，建议为多少。
