### ISSUE TITLE
datas参数问题

### ISSUE THREAD

**Issue by xiaok6666** [ZrO2Bit/Rane_RCE_Test#4]
此处可以填login抓包的全部参数，用于登录，实测不登录，只要ts足够大就能响应请求，请问这个是哪里来的啊，抓包没有datas参数

**Comment by ZrO2Bit** [comment]
把抓包获得的login请求里面的全部内容填进去就行了，直接复制进去就行，形如“t=12345678&v=xxxxxxx”

**Comment by xiaok6666** [comment]
> 把抓包获得的登录请求里面的全部内容填进去就行了，直接复制进去就行，形如“ t = 12345678＆v = xxxxxxx”

好的，我在抓包试下

**Comment by z2135** [comment]
> 把抓包获得的登录请求里面的全部内容填进去就行了，直接复制进去就行，形如“t=12345678&v=xxxxxxx”

请问要怎么才能抓到这个请求啊
