### ISSUE TITLE
单人刷分循环问题

### ISSUE THREAD

**Issue by CJXCK520** [ZrO2Bit/Rane_RCE_Test#6]
a=1
while a<9999:
    dat={}
    commandpost("/game/fbStart",dat)
    dat={"score":450,"step":10}
    time.sleep(9)
    commandpost("/game/fbSingle",dat)
    a+=1
博主，我设置了一个循环让他刷分，这个score我之前设置了最高680，后面设置成别的数字，它也默认680，而且循环10几次就爆红了，请问有什么解决方案吗，谢谢您的提示

**Comment by ZrO2Bit** [comment]
请勿大量发送请求干扰服务器运行及正常游戏秩序
