### ISSUE TITLE
燃鹅更新机制

### ISSUE THREAD

**Issue by CJXCK520** [ZrO2Bit/Rane_RCE_Test#7]
1.代刷奖品及代刷金币都被堵住了，并新增了作弊计数检测，命中检测5次以上将被封号；
2.奖品兑换时间暂时更改到了每天下午6点，并增加了成长值奖品的每日上限

你好作者，您能更新一下科技吗

**Comment by ZrO2Bit** [comment]
本开源项目旨在为官方提供预警，官方漏洞修复后不会再更新的
